services:
  - name: server
     plan: Starter
    plan: free
    type: web
    env: node
    repo: https://github.com/rahmamahdi02/sante-supplement-tracker/
    buildCommand: npm install && npm run build && cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString

databases:
  - name: db
    plan: free
    ipAllowList: []